import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Outfit } from "next/font/google";
import "./globals.css";
import Nav from "@/components/layout/nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ['latin'],
  weight: ['400']
})

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ['latin'],
  weight:['400','600', '700']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${outfit.variable} antialiased`}>
        {/* Navigation menu */}
        <Nav />

        {children}
      </body>
    </html>
  );
}
